### ISSUE TITLE
pretrained backbone model

### ISSUE THREAD

**Issue by mingx9527** [microsoft/voxelpose-pytorch#1]
Hi @Hanyue Tu  Thank for you code!  but the pretrained backbone model cannot download, open error, can you share other  link？？

**Comment by CHUNYUWANG** [comment]
Can you try this link https://1drv.ms/u/s!AjX41AtnTHeTjn3H9PGSLcbSC0bl?e=cw7SQg

**Comment by mingx9527** [comment]
@CHUNYUWANG Thank you!! It's OK
