### ISSUE TITLE
  "pose3d[:, 0:3] = pose3d[:, 0:3].dot(M)"  what means about M

### ISSUE THREAD

**Issue by ysp568** [microsoft/voxelpose-pytorch#11]
"pose3d[:, 0:3] = pose3d[:, 0:3].dot(M)"  in https://github.com/microsoft/voxelpose-pytorch/blob/main/lib/dataset/panoptic.py line 160
why dot M?

**Comment by ysp568** [comment]
[](url)

>

**Comment by ysp568** [comment]
"pose3d[:, 0:3] = pose3d[:, 0:3].dot(M)" in https://github.com/microsoft/voxelpose-pytorch/blob/main/lib/dataset/panoptic.py line 160
why dot M?

**Comment by CHUNYUWANG** [comment]
This is to change the coordinate system of poses in the Panoptic dataset such that we can use our projection code directly.

**Comment by ysp568** [comment]
> This is to change the coordinate system of poses in the Panoptic dataset such that we can use our projection code directly.

get ， to change the Panoptic coordinate system to math coordinate system(grid)

**Comment by ZichengDuan** [comment]
@special-yang @CHUNYUWANG Hi, I also have this confusion. According to panoptic toolbox guidance, the 3d coordinates are denoted as [x1, y1, z1], while the transformation matrix M will transfer [x1, y1, z1] into [x1, z1, -y1]. I still don't get the meaning of this. Could you please share your insights in this translation matrix? Many thanks.
