### ISSUE TITLE
I get an AP = 0

### ISSUE THREAD

**Issue by sudo-vinnie** [microsoft/voxelpose-pytorch#14]
Am I the only one getting this error ?
What can I do ?
```
Epoch: 9

Test: [0/645]	Time: 2.164s (2.164s)	Speed: 9.2 samples/s	Data: 1.694s (1.694s)	Memory 200613376.0
Test: [0/645]	Time: 2.164s (2.164s)	Speed: 9.2 samples/s	Data: 1.694s (1.694s)	Memory 200613376.0
Test: [100/645]	Time: 0.406s (0.452s)	Speed: 49.3 samples/s	Data: 0.000s (0.049s)	Memory 200613376.0
Test: [100/645]	Time: 0.406s (0.452s)	Speed: 49.3 samples/s	Data: 0.000s (0.049s)	Memory 200613376.0
Test: [200/645]	Time: 0.379s (0.438s)	Speed: 52.7 samples/s	Data: 0.000s (0.041s)	Memory 200613376.0
Test: [200/645]	Time: 0.379s (0.438s)	Speed: 52.7 samples/s	Data: 0.000s (0.041s)	Memory 200613376.0
Test: [300/645]	Time: 0.378s (0.431s)	Speed: 52.9 samples/s	Data: 0.000s (0.037s)	Memory 200613376.0
Test: [300/645]	Time: 0.378s (0.431s)	Speed: 52.9 samples/s	Data: 0.000s (0.037s)	Memory 200613376.0
Test: [400/645]	Time: 0.415s (0.426s)	Speed: 48.2 samples/s	Data: 0.000s (0.035s)	Memory 200613376.0
Test: [400/645]	Time: 0.415s (0.426s)	Speed: 48.2 samples/s	Data: 0.000s (0.035s)	Memory 200613376.0
Test: [500/645]	Time: 0.420s (0.424s)	Speed: 47.7 samples/s	Data: 0.000s (0.034s)	Memory 200613376.0
Test: [500/645]	Time: 0.420s (0.424s)	Speed: 47.7 samples/s	Data: 0.000s (0.034s)	Memory 200613376.0
Test: [600/645]	Time: 0.378s (0.423s)	Speed: 52.9 samples/s	Data: 0.000s (0.034s)	Memory 200613376.0
Test: [600/645]	Time: 0.378s (0.423s)	Speed: 52.9 samples/s	Data: 0.000s (0.034s)	Memory 200613376.0
Test: [644/645]	Time: 0.373s (0.425s)	Speed: 53.5 samples/s	Data: 0.000s (0.036s)	Memory 200613376.0
Test: [644/645]	Time: 0.373s (0.425s)	Speed: 53.5 samples/s	Data: 0.000s (0.036s)	Memory 200613376.0
ap@25: 0.0000	ap@50: 0.0000	ap@75: 0.0000	ap@100: 0.0000	ap@125: 0.0000	ap@150: 0.0000	recall@500mm: 0.0000	mpjpe@500mm: inf
ap@25: 0.0000	ap@50: 0.0000	ap@75: 0.0000	ap@100: 0.0000	ap@125: 0.0000	ap@150: 0.0000	recall@500mm: 0.0000	mpjpe@500mm: inf
```

**Comment by zhangyux15** [comment]
I got the same problem... how do you solve that

**Comment by Mosh-Wang** [comment]
> Am I the only one getting this error ? What can I do ?
> 
> ```
> Epoch: 9
> 
> Test: [0/645]	Time: 2.164s (2.164s)	Speed: 9.2 samples/s	Data: 1.694s (1.694s)	Memory 200613376.0
> Test: [0/645]	Time: 2.164s (2.164s)	Speed: 9.2 samples/s	Data: 1.694s (1.694s)	Memory 200613376.0
> Test: [100/645]	Time: 0.406s (0.452s)	Speed: 49.3 samples/s	Data: 0.000s (0.049s)	Memory 200613376.0
> Test: [100/645]	Time: 0.406s (0.452s)	Speed: 49.3 samples/s	Data: 0.000s (0.049s)	Memory 200613376.0
> Test: [200/645]	Time: 0.379s (0.438s)	Speed: 52.7 samples/s	Data: 0.000s (0.041s)	Memory 200613376.0
> Test: [200/645]	Time: 0.379s (0.438s)	Speed: 52.7 samples/s	Data: 0.000s (0.041s)	Memory 200613376.0
> Test: [300/645]	Time: 0.378s (0.431s)	Speed: 52.9 samples/s	Data: 0.000s (0.037s)	Memory 200613376.0
> Test: [300/645]	Time: 0.378s (0.431s)	Speed: 52.9 samples/s	Data: 0.000s (0.037s)	Memory 200613376.0
> Test: [400/645]	Time: 0.415s (0.426s)	Speed: 48.2 samples/s	Data: 0.000s (0.035s)	Memory 200613376.0
> Test: [400/645]	Time: 0.415s (0.426s)	Speed: 48.2 samples/s	Data: 0.000s (0.035s)	Memory 200613376.0
> Test: [500/645]	Time: 0.420s (0.424s)	Speed: 47.7 samples/s	Data: 0.000s (0.034s)	Memory 200613376.0
> Test: [500/645]	Time: 0.420s (0.424s)	Speed: 47.7 samples/s	Data: 0.000s (0.034s)	Memory 200613376.0
> Test: [600/645]	Time: 0.378s (0.423s)	Speed: 52.9 samples/s	Data: 0.000s (0.034s)	Memory 200613376.0
> Test: [600/645]	Time: 0.378s (0.423s)	Speed: 52.9 samples/s	Data: 0.000s (0.034s)	Memory 200613376.0
> Test: [644/645]	Time: 0.373s (0.425s)	Speed: 53.5 samples/s	Data: 0.000s (0.036s)	Memory 200613376.0
> Test: [644/645]	Time: 0.373s (0.425s)	Speed: 53.5 samples/s	Data: 0.000s (0.036s)	Memory 200613376.0
> ap@25: 0.0000	ap@50: 0.0000	ap@75: 0.0000	ap@100: 0.0000	ap@125: 0.0000	ap@150: 0.0000	recall@500mm: 0.0000	mpjpe@500mm: inf
> ap@25: 0.0000	ap@50: 0.0000	ap@75: 0.0000	ap@100: 0.0000	ap@125: 0.0000	ap@150: 0.0000	recall@500mm: 0.0000	mpjpe@500mm: inf
> ```

Sorry, I also encountered this problem. I would like to ask how did you solve this problem in the end?

**Comment by Mosh-Wang** [comment]
> I got the same problem... how do you solve that

Sorry, I also encountered this problem. I would like to ask how did you solve this problem in the end?
