### ISSUE TITLE
Different Projection Formulas

### ISSUE THREAD

**Issue by zhangyahu1** [microsoft/voxelpose-pytorch#5]
Thanks for sharing your nice work!

I notice you use two different formulas to trasnsform 3D pose from the world coordinate to the camera coordinate when processing shelf and CMU panoptic datasets, i.e. x = np.dot(R, X) + t and x = R.dot(X - t). Why not use the same formula?

**Comment by CHUNYUWANG** [comment]
This is because different datasets use different definitions of t.

**Comment by zhangyahu1** [comment]
Thanks!
